# Generated by Django 4.2.7 on 2024-08-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
