# Generated by Django 4.2.7 on 2024-08-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secuityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.CharField(max_length=500)),
                ('hobby', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
