# Generated by Django 4.2.7 on 2024-09-04 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secuityapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdate',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 4), null=True),
        ),
    ]
