# Generated by Django 4.2.7 on 2024-09-06 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secuityapp', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='createdate',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 6), null=True),
        ),
    ]
